name: BuildAndDeployAPK

on:
  push:
    paths:
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      apk_name: Niraj
      APK_VERSION: 1.0.97

    steps:
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Update AndroidManifest.xml
        run: |
          sed -i "s/android:label=\"[^\"]*\"/android:label=\"${{ env.apk_name }}\"/" app/src/main/AndroidManifest.xml

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Set up Git
        run: |
          git config --global user.name "T-InstaApp"
          git config --global user.email "hello@instaapp.online"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.97 # Replace with your desired tag name
          release_name: Release v1.0.97 # Replace with your desired release name
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FOR_TEST_REPO }}

      - name: Debug create_release outputs
        run: |
          echo "Create Release Outputs: ${{ toJson(steps.create_release.outputs) }}"
      
      - name: Save Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: instaapp.online@gmail.com
          password: ${{ secrets.GMAIL_TOKEN }}
          from: instaapp.online@gmail.com
          subject: APK Build Notification
          body: |
            Here is the link to download the APK:
            ${{ steps.upload_apk.outputs.browser_download_url }}
          to: niraj.kumar@tissatech.com,vishal.upadhyay@tissatech.com

      - name: Call API
        run: |
          export BASE_URL="https://restaurant60-be-dev-xtpocjmkpa-uw.a.run.app/app-url-update"
          export type="Android"
          export restaurant_id="239"
          export url="${{ steps.upload_apk.outputs.browser_download_url }}"
          export API_URL="$BASE_URL/?url=$url&type=$type&restaurant_id=$restaurant_id"
          echo "Uploading APK: $API_URL"
          response=$(curl -X GET $API_URL)
          echo "API Response: $response"
        shell: bash