name: BuildAndDeployAPK

on:
  push:
    paths:
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      apk_name: SKAPP1
      APK_VERSION: 1.1.51
      Company_Name: Carvana
      email: niraj.kumar@tissatech.com,vishal.upadhyay@tissatech.com
      logo_url: https://images.vexels.com/media/users/3/142789/isolated/preview/2bfb04ad814c4995f0c537c68db5cd0b-multicolor-swirls-circle-logo.png

    steps:
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Download new logo
        run: curl -o new_logo.png ${{ env.logo_url }}
      
      - name: Replace logo in app
        run: |
          # Assuming your app's logo is stored at app/src/main/res/drawable/logo.png
          cp new_logo.png app/src/main/res/drawable/logo.png

      - name: Update AndroidManifest.xml
        run: |
          sed -i "s/android:label=\"[^\"]*\"/android:label=\"${{ env.apk_name }}\"/" app/src/main/AndroidManifest.xml
          sed -i "s#android:icon=\"[^\"]*\"#android:icon=\"@drawable/logo\"#" app/src/main/AndroidManifest.xml
          
      - name: Determine current version
        id: determine_version
        run: |
          echo "CURRENT_VERSION=${{ env.APK_VERSION }}" >> $GITHUB_ENV

      - name: Update versionName in build.gradle
        run: |
          sed -i "s/versionName \".*\"/versionName \"${{ env.APK_VERSION }}\"/" app/build.gradle
        working-directory: ${{ github.workspace }}

      - name: Commit changes and push
        run: |
          git config --local user.email "hello@instaapp.online"
          git config --local user.name "T-InstaApp"
          git add app/build.gradle app/src/main/AndroidManifest.xml app/src/main/res/drawable/logo.png
          git commit -m "Update versionName and app icon"
          git push --force

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Set up Git
        run: |
          git config --global user.name "T-InstaApp"
          git config --global user.email "hello@instaapp.online"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.1.50 # Replace with your desired tag name
          release_name: Release v1.1.50 # Replace with your desired release name
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Release Asset Name
        run: echo "APK_NAME=${{ env.apk_name }}.apk" >> $GITHUB_ENV

      - name: Rename and Upload APK
        run: |
          APK_NAME="${{ env.apk_name }}.apk" # Remove -debug from the APK name
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/$APK_NAME
          echo "Uploading APK: $APK_NAME"
        shell: bash

      - name: Upload APK as Release Asset
        id: upload_apk
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/${{ env.APK_NAME }}
          asset_name: ${{ env.APK_NAME }}
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
